name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade buildozer cython virtualenv

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip openjdk-17-jdk autoconf automake cmake unzip zlib1g-dev libffi-dev libssl-dev libncurses5-dev

      - name: Install Android SDK & AIDL
        run: |
          sudo apt install -y android-sdk adb
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;31.0.0" "cmdline-tools;latest"

      - name: Initialize Buildozer
        run: buildozer init

      - name: Build APK
        run: buildozer -v android debug
